name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pytest flake8 bandit

      # Lint only our test suite for now to keep CI green
      - name: Lint (tests only)
        run: flake8 tests

      # Bandit as advisory first; we will enforce later
      - name: Security scan (non-blocking)
        run: bandit -r . -x tests || true

      - name: Tests
        run: pytest -q
